// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6lEm9fUhkHUigwLDFk07YDPwkkv7Xcic',
    appId: '1:34095983586:web:5cf502a730440db9c427bb',
    messagingSenderId: '34095983586',
    projectId: 'fine-aid-9e0a9',
    authDomain: 'fine-aid-9e0a9.firebaseapp.com',
    storageBucket: 'fine-aid-9e0a9.firebasestorage.app',
    measurementId: 'G-Q1Q5MF0LWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3ffpdzLEApIVNq7PA8IQmN94_lhLidQ',
    appId: '1:34095983586:android:d1ac917cc7ecea4ec427bb',
    messagingSenderId: '34095983586',
    projectId: 'fine-aid-9e0a9',
    storageBucket: 'fine-aid-9e0a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIeDcanfFK3m07PHKL4tr-Ogs90Rstt8',
    appId: '1:34095983586:ios:357e10561b841cd5c427bb',
    messagingSenderId: '34095983586',
    projectId: 'fine-aid-9e0a9',
    storageBucket: 'fine-aid-9e0a9.firebasestorage.app',
    iosBundleId: 'com.example.fineAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfIeDcanfFK3m07PHKL4tr-Ogs90Rstt8',
    appId: '1:34095983586:ios:357e10561b841cd5c427bb',
    messagingSenderId: '34095983586',
    projectId: 'fine-aid-9e0a9',
    storageBucket: 'fine-aid-9e0a9.firebasestorage.app',
    iosBundleId: 'com.example.fineAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6lEm9fUhkHUigwLDFk07YDPwkkv7Xcic',
    appId: '1:34095983586:web:4a5bd39596a05a9dc427bb',
    messagingSenderId: '34095983586',
    projectId: 'fine-aid-9e0a9',
    authDomain: 'fine-aid-9e0a9.firebaseapp.com',
    storageBucket: 'fine-aid-9e0a9.firebasestorage.app',
    measurementId: 'G-ZCNZJ5LMSF',
  );
}
